language: java
jdk: openjdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
cache:
  directories:
  - "~/.m2/repository"
env:
  global:
  - secure: ejxVfhRTQ9KhWriGZa5Sb6gcaCEsDsE4X+li4y+BKfTvCf96VoIouUVJq74s4B1h7ClC2eh9PrEDSc+nYyzRDjmMcVWXQYS0gXFYAPVYY3bd4EoYWCW7FlHlT8636sJ1sVG4hnDe2YXxksf/wn9WuPh/HYro3v14VXk6SxbVkpc=
  - secure: bdwuG11/pTdxMZHnlOJ1o6rfYH7HfA2Fm9NqikNx60bRcJLfqtcb9YikhTwlpoj3T3lzWyGtTtYvIlV7wG5xTqOyse5LENhLCltzd4lqNztcIetlgzbjEJJ5xUoXn+HBxne/ZfVotbEkpN0h3OpQ/ObfUUISV80RjvinLwP8hPk=
  - secure: R1XXsoyk9wE8oBuH2jnnTDgXDzfhWIrTA5PFEbzdepVz4v/Uy/wLGsskohIGr+Vx9Y7IebTBCLkmIQm8ThPxu0e3Z6klzTHUDTgQxXwo9UEWM1sEYK12IXFRTeqWokSjfaenq4AN4tcq1Bvf7/K1czgE2OnCw8WYnA/aCc2TqJ0=
  - secure: Q3UR41xncmDDVLi0wBa2zv7PsJidTX85PCoEBlZKj2EdD0+P1duJIZd6vnQ0/b/ifmtNVA8Ny3SJpfoTPraVeIja78p008jnHO+8bF+BZD6rAkzAf9mm4m640L646fuLN7hMdaE0+SZjjWDh6ZXR5lbnNOL9qozaiq8SHWrAp+4=
